//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labaratorka01d01.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchet
    {
        public int ID { get; set; }
        public int NumbChet { get; set; }
        public int MothPay { get; set; }
        public decimal Rate { get; set; }
        public int Kw { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
